### ISSUE TITLE
Getting an error when using ResourcePlugin

### ISSUE THREAD

**Issue by myarasi8** [cwellsx/electron-forge-resource-plugin#1]
Hello,

This isn't an issue, more of a question. 

When I run npm run make, about 25 minutes into it I am getting this error: 
`An unhandled rejection has occurred inside Forge:
Error: EEXIST: file already exists, mkdir 'C:\Users\JOHN~1.SMI\AppData\Local\Temp\electron-packager\win32-x64\micro-host-win32-x64-07ZxYp\resources\core'`

Below is my forge.config.js:
```// import { ResourcePlugin } from 'electron-forge-resource-plugin';
const { ResourcePlugin } = require ('electron-forge-resource-plugin');

module.exports = {
  packagerConfig: {
    asar: true,
  },
  rebuildConfig: {},
  makers: [
    {
      name: '@electron-forge/maker-squirrel',
      config: {
        authors: 'John',
        description: 'Prototype App'
      },
    },
    {
      name: '@electron-forge/maker-zip',
      platforms: ['darwin'],
    },
    {
      name: '@electron-forge/maker-deb',
      config: {},
    },
    {
      name: '@electron-forge/maker-rpm',
      config: {},
    },
  ],
  plugins: [
    {
      name: '@electron-forge/plugin-auto-unpack-natives',
      config: {},
    },
    new ResourcePlugin({
      env: "CORE_EXE",
      path: "../ElectronCgiDotNetDemoTwo/ElectronCgiDotNetDemoTwo/bin/Release/net6.0/ElectronCgiDotNetDemoTwo.exe",
      build: {
        command: "dotnet.exe build ../ElectronCgiDotNetDemoTwo/ElectronCgiDotNetDemoTwo/ElectronCgiDotNetDemoTwo.csproj --verbosity normal --configuration Release",
        sources: "../ElectronCgiDotNetDemoTwo/ElectronCgiDotNetDemoTwo/",
      },
      package: {
        dirname: "core",
      },
      verbose: true,
    })
  ],
};
```

I was wondering if you came across this or if you have any idea how to resolve it? I ran this command from a cmd prompt with administrator privileges. Additionally, my React + Electron + .NET app doesn't have the following files in it:

1. webpack.main.config.js
2. webpack.plugins.js
3. webpack.renderer.config.js
4. webpack.rules.js

If I remove the ResoucePlugin from forge.config.js, I'm able to build the exe fine without those files so I'm not sure if/why they are needed. I do have a web.config.js and a tsconfig.json.

Please let me know and thanks in advance!

**Comment by cwellsx** [comment]
> I was wondering if you came across this or if you have any idea how to resolve it?

I didn't and I haven't, sorry.

Also I am busy and will soon be away for a month, so I can't investigate this at the moment. Good luck!

25 minutes sounds like a very long build.

IIRC when I developed this I sometimes launched the build script within VS Code's debugger.

One to-do -- possibly unrelated to your problem -- might be update this to use or to test it with more recent copy of Electron Forge.

**Comment by Komar0ff** [comment]
The exact same problem has arisen.  
Config looks like this:
```
const config: ForgeConfig = {
  packagerConfig: {
    extraResource: "./LICENSE",
  },
  rebuildConfig: {},
  makers: [new MakerSquirrel({}), new MakerZIP({}, ["darwin"]), new MakerRpm({}), new MakerDeb({})],
  plugins: [
    new WebpackPlugin({
      mainConfig,
      renderer: {
        config: rendererConfig,
        entryPoints: [
          {
            html: "./src/renderer/index.html",
            js: "./src/renderer/index.ts",
            name: "main_window",
            preload: {
              js: "./src/preload/index.ts",
            },
          },
        ],
      },
    }),
    new ResourcePlugin({
      env: "CORE_EXE",
      path: "./src.dotnet/bin/Release/net7.0/Core",
      build: {
        command: "/usr/local/share/dotnet/dotnet build ./src.dotnet/Core.csproj --verbosity normal --configuration Release",
        sources: "./src.dotnet/",
      },
      package: {
        dirname: "core",
      },
      verbose: true,
    }),
  ],
};
```
I execute the command npm run make. And at some point I get an error:
```
"An unhandled rejection has occurred inside Forge:
Error: EEXIST: file already exists, mkdir '/var/folders/z_/5k47sjm15ss108lh72dnqhwr0000gn/T/electron-packager/darwin-x64/my-new-app-darwin-x64-Jkf3k9/my-new-app.app/Contents/Resources/core'""
```

OS: macOS Ventura 13.6 
electron: 21.2.2
electron-forge: 6.4.2

It's pretty critical to me. Any idea what this is about and how I can fix it quickly?

**Comment by Komar0ff** [comment]
on linux the error is reproduced too

**Comment by cwellsx** [comment]
I found the same error.
I guess the unwanted behaviour was introduced with a later version of Electron Forge.

- [A custom plugin's init and hook methods are invoked twice during make](https://github.com/electron/forge/issues/3452)

I edited, and uploaded to npm, a new version of this plugin which:
- Fixes this error -- https://github.com/cwellsx/electron-forge-resource-plugin/commit/5df1deb6113c565275e16c67bfb50bd83dfe65f8
- Supports or requires the latest version of Electron Forge i.e. 7.2.0

Please let me know whether this does or doesn't fix it for you (I assume it does, it fixed it for me).
